---
abstract: 'A simple parser for Makefiles'
author:
  - "Zhang \"agentzh\" Yichun, C<< <agentzh@gmail.com> >>"
build_requires:
  ExtUtils::MakeMaker: 6.42
  IPC::Run3: 0.036
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Makefile-Parser
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0
  Class::Trigger: 0.13
  Cwd: 0
  File::Slurp: 0
  File::Spec: 0
  Filter::Util::Call: 0
  List::MoreUtils: 0
  List::Util: 0
  Makefile::DOM: 0.003
  Text::Balanced: 0
  Time::HiRes: 0
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/agentzh/makefile-parser-pm
version: 0.211
