--- 
abstract: A simple parser for Makefiles
author: 
  - Agent Zhang, C<< <agentzh@yahoo.cn> >>
build_requires: 
  IPC::Run3: 0.036
  Test::More: 0.62
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Makefile-Parser
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  Class::Trigger: 0.13
  Cwd: 0
  File::Slurp: 0
  File::Spec: 0
  List::MoreUtils: 0
  List::Util: 0
  Makefile::DOM: 0.003
  Text::Balanced: 0
  Time::HiRes: 0
  perl: 5.004
version: 0.207
